# Generated by Django 3.0.5 on 2021-01-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_func', '0002_webseo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webseo',
            name='brief',
            field=models.TextField(blank=True, max_length=70, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='webseo',
            name='keywords',
            field=models.CharField(blank=True, max_length=70, verbose_name='关键字'),
        ),
    ]
