# Generated by Django 3.0.5 on 2021-01-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_func', '0003_auto_20210119_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webseo',
            old_name='brief',
            new_name='descriptison',
        ),
    ]
