# Generated by Django 3.0.5 on 2021-01-27 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_func', '0004_auto_20210119_2314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebSEO',
        ),
    ]
