# Generated by Django 3.0.5 on 2021-03-11 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_func', '0005_delete_webseo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name_plural': '阅读数'},
        ),
    ]
