# Generated by Django 3.0.5 on 2021-02-16 19:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gossip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gossip',
            name='body',
        ),
        migrations.AddField(
            model_name='gossip',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1, verbose_name='文本'),
            preserve_default=False,
        ),
    ]
