# Generated by Django 3.0.5 on 2021-01-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='descriptison',
            field=models.CharField(blank=True, max_length=70, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=70, verbose_name='关键词'),
        ),
    ]
