# Generated by Django 3.0.5 on 2021-02-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeblog',
            name='descriptison',
            field=models.CharField(blank=True, max_length=200, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='codeblog',
            name='keywords',
            field=models.CharField(blank=True, max_length=100, verbose_name='关键词'),
        ),
    ]
