# Generated by Django 3.0.5 on 2021-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='体重')),
                ('record_date', models.DateTimeField(auto_now_add=True, verbose_name='记录日期')),
            ],
            options={
                'verbose_name_plural': '健康',
                'ordering': ['-record_date'],
            },
        ),
    ]
