# Generated by Django 3.0.5 on 2021-02-05 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20210201_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_time'], 'verbose_name_plural': '评论'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='评论时间'),
            preserve_default=False,
        ),
    ]
