# Generated by Django 3.0.5 on 2021-02-10 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20210205_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
