# Generated by Django 3.0.5 on 2021-02-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arch_blog', '0003_auto_20210212_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name_plural': '标签'},
        ),
    ]
